version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
     - ${JENKINS_WEB_PORT}:8080
    volumes:
     - ./jenkins_configuration:/var/jenkins_home
     - /var/run/docker.sock:/var/run/docker.sock
